config/routes.rb
Rails.application.routes.draw do
  resources :participants

  root 'static_pages#home'

  resources :static_pages do
    collection do
      get :thank_you
    end
  end

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessor :checkbox

  def self.assign_peeps
    senders = Participant.all.map{ |p| [p.id, p.name, p.email, p.city]}.shuffle
    receivers = Participant.all.map{ |p| [p.id, p.name, p.email, p.city]}.shuffle
    matches = []
    while (!self.match(senders, receivers, matches))
      matches = []
      senders = Participant.all.map{ |p| [p.id, p.name, p.email, p.city]}.shuffle
    end
    return matches
  end

  def self.match(senders, receivers, matches)
    receivers.each do |match|
      sender = senders.pop
      if (sender.second == match.second) || ( sender.last == match.last )
        return false
      end
      matches.push [match, sender]
    end
    return true
  end
 
  def self.get_and_send
    matches = self.assign_peeps
    matches.each do |match|
      @sender = Participant.find(match.first.first)
      @reciever = Participant.find(match.second.first)
      MatchMailer.match_mail(@sender, @reciever).deliver_now!      
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to thank_you_static_pages_path, notice: 'Thank you! You have been recorded. Standard Messaging Rates Apply.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :email, :address)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def thank_you
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiftEX</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <audio src="/audio/silent-night-disco.mp3" autoplay loop ></audio>
</head>
<body>
<div class="text-center">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div class="text-center"><h1 class="christmas">HO HO HO! MERRY CHIRSTMAS!</h1></div>
<%= image_tag("what-do-you-want-for-christmas.gif")%>
<%= image_tag("presents-under-tree.gif")%>
<%= image_tag("santa-dancing-1.gif")%>
<%= image_tag("frosty-in-sleigh-animated.gif")%>
<%= image_tag("santa-delivering-gifts-1.gif")%>
<%= image_tag("merry-christmas-elf.gif")%>
</div>

<%= yield %>

</body>
</html>

app/views/participants/_form.html.erb
<%= simple_form_for(@participant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.email %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/static_pages/home.html.erb
<div class="row">
<div class="col-md-2 col-md-offset-5 col-sm-6 col-sm-offset-3 text-center">
<%= simple_form_for Participant.new, id: "new-peep" do |f| %>
  <%= f.error_notification %>

  <div class="christmas" style="color:white;"><h4 style="color:white;">Fill Out Form Below to Enter Gift Exchange!</h4>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :address %>
    <%= f.input 'checkbox', label: false, as: :check_boxes, collection: ["Yes! Please send me facts about Christmas!"] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enter Exchange!", style: "color:black;" %>
  </div>
  </div>
<% end %>
</div>
</div>
<script>
  $('#new-peep').submit(function (event) {
    if ($("#participant_checkbox_yes_please_send_me_facts_about_christmas:checked").length > 0){
    }else{
      preventDefault();
      alert("Warning! You have not indicated you want christmas facts!");
    }
    
  });
  
</script>

app/views/static_pages/thank_you.html.erb
<div class="christmas text-center"><h1>Thank You and God Bless!</h1></div>